name: music_dictionary
description: A new Flutter project.

publish_to: "none"

version: 2.0.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.9.0
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  shared_preferences: ^2.1.0
  cloud_firestore: ^4.5.0
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  firebase_crashlytics: ^3.2.0
  google_mobile_ads: ^3.0.0
  firebase_remote_config: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  bloc_test: ^9.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash_screen_image.png
    - assets/images/splash_screen_image_4x.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
