// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFFxjMFEdo0Dembdgwj83nZ_n_BdPHOz4',
    appId: '1:205061030092:android:57df7f1a10859037e58269',
    messagingSenderId: '205061030092',
    projectId: 'musicdictionary-34dd2',
    databaseURL: 'https://musicdictionary-34dd2-default-rtdb.firebaseio.com',
    storageBucket: 'musicdictionary-34dd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3reUPASlAyWxas6gMvrqJ6YzmKN1jU4w',
    appId: '1:205061030092:ios:b8ec4c1cf38b0d36e58269',
    messagingSenderId: '205061030092',
    projectId: 'musicdictionary-34dd2',
    databaseURL: 'https://musicdictionary-34dd2-default-rtdb.firebaseio.com',
    storageBucket: 'musicdictionary-34dd2.firebasestorage.app',
    iosBundleId: 'com.renanschotten.musicDictionary',
  );

}